In [1]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from datetime import datetime

In [2]:
data = pd.read_csv("358057080902248.csv")

In [6]:
data.describe()

,358057080902248,7.0,3000.0,1570599955635,15,12,27.9,3903,990,Unnamed: 15,Unnamed: 16,Unnamed: 17
count,2.296290e+05,208908.0,229629.0,2.296290e+05,229629.000000,229629.000000,229629.000000,229629.000000,229629.000000,0.0,0.0,0.0
mean,3.580571e+14,7.0,3000.0,1.570989e+12,52.065088,24.952301,30.882216,3903.865762,247.000091,NaN,NaN,NaN
std,0.000000e+00,0.0,0.0,2.590113e+08,29.228374,7.996979,2.653555,179.748524,276.397256,NaN,NaN,NaN
min,3.580571e+14,7.0,3000.0,1.570600e+12,0.000000,0.000000,24.500000,3390.000000,0.000000,NaN,NaN,NaN
25%,3.580571e+14,7.0,3000.0,1.570749e+12,29.000000,25.000000,29.000000,3772.000000,39.000000,NaN,NaN,NaN
50%,3.580571e+14,7.0,3000.0,1.571079e+12,52.000000,25.000000,31.000000,3868.000000,148.000000,NaN,NaN,NaN
75%,3.580571e+14,7.0,3000.0,1.571201e+12,75.000000,25.000000,32.800000,4026.000000,389.000000,NaN,NaN,NaN
max,3.580571e+14,7.0,3000.0,1.571405e+12,100.000000,100.000000,36.700000,4283.000000,1544.000000,NaN,NaN,NaN